# Basic of Python
## Questions from Datacamp Practice
### Created by Sohail Ahmed 3-1-2023

In [1]:
# Import Library
import pandas as pd
import numpy as np

In [6]:
costs = [8,5,7,9]
print(np.array(costs))

[8 5 7 9]


In [20]:
fruit = {"apples":{"cost":3, "ubits":100},
         "bananas":{"cost":1, "units":80},
         "grapes":{"cost":5, "units":500}}
print(fruit["bananas"]["units"])

80


In [22]:
"three">"one"

True

In [35]:
# DataFrame Practice
datacamp = pd.DataFrame({"chapter":[1,2,3], "course":["ds","dv","db"], "tech":["py", "R", 'sql']})
datacamp

chapter course tech
0        1     ds   py
1        2     dv    R
2        3     db  sql

In [36]:
for lab, row in datacamp.iterrows():
    print(lab)
    print(row)

0
chapter     1
course     ds
tech       py
Name: 0, dtype: object
1
chapter     2
course     dv
tech        R
Name: 1, dtype: object
2
chapter      3
course      db
tech       sql
Name: 2, dtype: object


In [41]:
fruits = {"nuts":230, "lemon":200,"olives":250}
fruits
fruits["lemon"]

200

In [44]:
words = "jump"
for letter in words:
    print(letter)

j
u
m
p


In [48]:
datacamp = {"course":"pythoon", "level": "intermediate", "lesson":{"dictiionaries": "python", "list":"r"}}
datacamp["lesson"]["list"]="sql"
datacamp

{'course': 'pythoon',
 'level': 'intermediate',
 'lesson': {'dictiionaries': 'python', 'list': 'sql'}}

In [15]:
array = np.array([1,2,3,4,5,6])
array
array.ndim

4

#### We can reshape array into any dim


In [8]:
array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array3 = array1.reshape(2,2,3)
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
# Another  way of reshaping
array = np.array([1,2,3,4,5,6], ndmin=4)
array
array.ndim

4